// Product
export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";
export const FILTER_PRODUCT = "FILTER_PRODUCT";


// Cart
export const GET_CART_ITEMS="GET_CART_ITEMS";
export const ADD_CART_ITEMS="ADD_CART_ITEMS";
export const REMOVE_CART_ITEMS="REMOVE_CART_ITEMS";
export const CHANGE_CART_ITEMS="CHANGE_CART_ITEMS";
